### ISSUE TITLE
brcypt-ruby name change

### ISSUE THREAD

**Issue by rupe** [datamapper/dm-types#70]
Update the 'bcrypt-ruby' gem requirement to just 'bcrypt', as the gems name has been changed and requiring the former results in an informational messages being displayed.

**Comment by tpitale** [comment]
This is fixed on master afaict.

**Comment by Choms** [comment]
Hi,
Would you mind issuing a new release so when we require this gem we don't get that error message anymore? Even though is fixed on master, the latest gem (dm-types 1.2.2) is still requiring bcrypt-ruby.
Thanks!

**Comment by tpitale** [comment]
Many things have to happen across all the DM repos before we can release new gems. Nobody seems willing to help maintain, so that seems unlikely to happen.

Bundler supports using git repos quite easily. Please help by testing that and letting us know if that fixes the issue @Choms.
