### ISSUE TITLE
Missing code in release v1.2.2

### ISSUE THREAD

**Issue by tpitale** [datamapper/dm-types#78]
https://github.com/datamapper/dm-types/compare/v1.2.2...master says it should include the code from PR #50. Unfortunately, the released gem on rubygems does not appear to have this code included in the `dirty_minder.rb`. Can a v1.2.3 be release to fix the rubygem?

**Comment by julienma** [comment]
@tpitale I have the same issue, but can't find a v1.2.3 of the gem (or any update actually).
Why is that issue closed? Is there any way to workaround this?
Thanks.

**Comment by tpitale** [comment]
I can't recall at the moment what I ended up doing to get around this. It may be in a different release branch that's used for gems (if master is not used). I'm also not sure why I didn't comment when I closed it.

**Comment by julienma** [comment]
Ok, thanks anyway.
I ended up using my own (fixed) fork: https://github.com/datamapper/dm-types/issues/77#issuecomment-192359563
